### ISSUE TITLE
Change Complete User Interface of the Web Application

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/VoteX#38]
## TODO

- [x] Home
- [x] All Candidates | All Voters | Approved Candidates
  - [x] Candidate Cards
  - [x] Conditional Buttons
- [x] Pre-Register Phase
  - [x] Upload Aadhaar Card
  - [x] OTP Verification
  - [x] Face Registration
- [x] Register Candidate | Register Voter
- [x] Candidate Details | Voter Details
- [x] Owner Tunings
- [x] Vote Page
  - [x] Face Verification
- [x] Update Voter | Update Candidate
