### ISSUE TITLE
Complete Recognition and Verification

### ISSUE THREAD

**Issue by soorya-u** [soorya-u/VoteX#40]
## TODO

- Phone Number Recognition
  - [x] Scan User Phone Number in Aadhaar Card
  - [x] Save Phone Number in Redis
- Phone Number Verification
  - [x] Verify OTP
  - [x] Set Voter Status to Approved in Stellar

- Face Registration
  - [x] Check if Face is Recognizable
  - [x] Save it in Pinata
  - [x] Set IPFS Hash in Stellar Contract
- Face Verification
  - [x] Fetch Face Image from Pinata through Stellar
  - [x] Compare Faces
  - [x] Output the result
